version: '3.9'
services:
  application:
    build: .
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DSN: postgresql://postgres:password@db/postgres
      POSTGRES_SERVER: ${DB_SERVER}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - enrollment

  db:
    image: postgres:15.2-alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    networks:
      - enrollment

networks:
  enrollment:
    driver: bridge
