version: '3.9'
services:
  db:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    restart: always
    networks:
      - enrollment
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 5s
      timeout: 5s
      retries: 5

  application:
    build: .
    restart: always
    environment:
      POSTGRES_DSN: postgresql://postgres:password@db/postgres
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - enrollment

networks:
  enrollment:
    driver: bridge
