"""Add courier

Revision ID: 6046bf76b908
Revises: 18ccceec8030
Create Date: 2023-05-14 21:00:54.934071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6046bf76b908'
down_revision = '18ccceec8030'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier',
    sa.Column('courier_id', sa.BigInteger(), nullable=False),
    sa.Column('courier_type', sa.Enum('foot', 'bike', 'auto', name='couriertype'), nullable=False),
    sa.Column('regions', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('working_hours', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('courier_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courier')
    # ### end Alembic commands ###
