"""Add group_orders and order_group

Revision ID: f7ab5149bdce
Revises: 6046bf76b908
Create Date: 2023-05-15 04:01:07.398865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ab5149bdce'
down_revision = '6046bf76b908'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_orders',
    sa.Column('group_order_id', sa.BigInteger(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['courier.courier_id'], ),
    sa.PrimaryKeyConstraint('group_order_id')
    )
    op.create_table('order_group',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('group_order_id', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False, default=False),
    sa.ForeignKeyConstraint(['group_order_id'], ['group_orders.group_order_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_group')
    op.drop_table('group_orders')
    # ### end Alembic commands ###
